name: genngxinzuboy
on:
  # push:
   schedule:
    - cron: '0 30 23 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31 * ? '
   workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install opencv-python requests 
      - name: Run gengxinsichuanip
        run: python ${{ github.workspace }}/udp_iptv2.0.py
     
      - name: Commit results
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            if [ -n "$(git status --porcelain)" ]; then
            git add *.m3u *.txt
            git commit -m "Automatic update"
            git push
            else
              echo "No changes detected, skipping commit."
            fi			
