name: gengxing

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install selenium requests futures eventlet
    - name: Install dependencies
      run: pip install opencv-python requests 
    - name: Install dependencies
      run: pip install Beautifulsoup4 requests 
    - name: Install dependencies
      run: pip install translate requests 
      
    - name: Run iptv
      run: python ${{ github.workspace }}/udp_iptv2.0.py
    - name: time
      run: date
