name: 酒店源采集

on:
  schedule:
    - cron: '0 2,6,10,14,18,22 * * *'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run itv.py
        run: python ${{ github.workspace }}/py/酒店源采集/itv.py
     
      - name: Run cctv.py
        run: python ${{ github.workspace }}/py/酒店源采集/cctv.py

      - name: Run weishi.py
        run: python ${{ github.workspace }}/py/酒店源采集/weishi.py 

      - name: Run qita.py
        run: python ${{ github.workspace }}/py/酒店源采集/qita.py    
        
      - name: Run iptv.py
        run: python ${{ github.workspace }}/py/酒店源采集/iptv.py
        
      - name: 提交更改
        run: |
          git config --local user.email "2856364053@qq.com"
          git config --local user.name "adminouyang"
          git add .
          git commit *.txt -m "action: `date`"
          git commit *.m3u -m "action: `date`"
          #git pull --rebase
          git push -f
