name: 酒店源采集

on:
  schedule:
    - cron: '0 2,6,10,14,18,22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run itv
        run: python ${{ github.workspace }}/py/酒店源采集/iptv.py
     
      - name: Run qita
        run: python ${{ github.workspace }}/py/酒店源采集/qita.py
          
      - name: 提交更改
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "2856364053@qq.com"
          git config --local user.name "adminouyang"
          git add .
          git commit *.txt -m "Update files from GitHub Actions"
          git commit *.m3u -m "Update files from GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:$(git branch --show-current)
